### ISSUE TITLE
Suggestion: Add Max Synergy with Wild Type Title Reward - Feral

### ISSUE THREAD

**Issue by nathanrhart** [keldaanCommunity/pokemonAutoChess#1565]
As title suggests, can we get a Title reward for max synergy for Wild types.

Perhaps call the title Feral?

(Apologies if in the wrong forum to post)

P.S. If I pretend it's a bug that it isn't included (when most/all others are), can I get Glitch Trainer? (username - Kronorox) 😂

**Comment by sylvainpolletvillard** [comment]
Discord is the place to discuss about game ideas: https://discord.com/channels/737230355039387749/1213044490076561408

Github is reserved for code / development issues
