### ISSUE TITLE
[Question] About trackers

### ISSUE THREAD

**Issue by dejalavidavolar** [keldaanCommunity/pokemonAutoChess#1928]
Hi! I hope you are doing well. I would like to know if it is possible to reduce trackers on the website. I mean, ublock and privacy badger detect the following trackers:

cdn.mxpnl.com
maxcdn.bootstrapcdn.com 
cdnjs.cloudflare.com 
www.gstatic.com 

I make this suggestion because i like the game and it would be more privacy-friendly.

Have a nice day/night!

**Comment by keldaan-ag** [comment]
we can safely remove mixpanel cdn
