### ISSUE TITLE
Frequent missing assets

### ISSUE THREAD

**Issue by Inspirateur** [keldaanCommunity/pokemonAutoChess#2238]
No clue about the bug except that very often we get black squares everywhere when launching a game (I assume some assets couldn't load) and black background. Happens like 1/2 games so it shouldn't be hard to reproduce. 

This makes the game borderline unplayable and I haven't been able to fix it by clearing the cache and reloading 🤷

**Comment by keldaan-ag** [comment]
I don't get why you are trying to play the game if it's boderline unplayable.

**Comment by Inspirateur** [comment]
Because I can play it roughly 1/2 games as I outlined :) 

Your reply seems like a lazy/bad faith argument to close the issue, but you know if you don't want any issues, you can state it somewhere in the README ! 

Btw this does not just happen to me, I can try to fetch some debugging info if you want, but you don't seem to care so it's not very encouraging 🙏 

Anyway the project is cool otherwise! ty

**Comment by Inspirateur** [comment]
Looks like this btw 
![image](https://github.com/user-attachments/assets/0078f7d3-24df-44cb-8cd4-8853287c1555)

**Comment by Wirby48** [comment]
@Inspirateur did you ever find a fix

**Comment by Inspirateur** [comment]
> @Inspirateur did you ever find a fix
> 

not that i recall unfortunately, but i stopped playing since

**Comment by Wirby48** [comment]
> > [@Inspirateur](https://github.com/Inspirateur) did you ever find a fix
> 
> not that i recall unfortunately, but i stopped playing since

very sad i've been trying to play all morning and it's just not possible
